const BASE={
'shawarma':{name:'Signature Shawarma',sizes:{'Lite':45,'Classic':55,'District Max':70},extras:{'Extra Chicken':8,'Extra Sausage':4,'Mixed Protein':12,'Extra Sauce':5,'Extra Cheese':10}},
'loaded-fries':{name:'Loaded Fries',sizes:{'Regular':70,'Medium':80,'Large':90},extras:{'Extra Chicken':15,'Extra Cheese':10,'Extra Sauce':10}},
'loaded-angwamo':{name:'Loaded Angwamo',sizes:{'Basic':60,'Classic':70,'Max · 5 Proteins':85},extras:{'Egg':6,'Sausage':8,'Chicken':15}},
'fried-rice':{name:'Fried Rice',sizes:{'Regular':65,'Classic':75,'District Max':85},extras:{'Extra Chicken':15,'Fried Egg':6,'Extra Sauce':5}},
'loaded-jollof':{name:'Loaded Jollof',sizes:{'Loaded Jollof':85},extras:{'Chicken':15,'Egg':6}},
'noodles':{name:'Noodles',sizes:{'Noodles':50},extras:{'Chicken':15,'Sausage':8,'Egg':6}},
'salad':{name:'District Salad',sizes:{'Regular':40,'Big Bowl':50,'District Bowl':55},extras:{}},
'burger':{name:'District Burger',sizes:{'Original':50,'Double District':60,'Big District':70},extras:{'Extra Patty':18,'Cheese':10,'Sausage':8,'Extra Sauce':5,'Fried Egg':6}}
};
const arr=v=>Array.isArray(v)?v:[];function normaliseProduct(raw,id){if(!raw)return BASE[id];const sizes={};arr(raw.sizes).forEach(x=>{const n=Array.isArray(x)?x[0]:x?.name,p=Number(Array.isArray(x)?x[1]:x?.price);if(n&&Number.isFinite(p))sizes[n]=p});const extras={};arr(raw.extras).forEach(x=>{const n=Array.isArray(x)?x[0]:x?.name,p=Number(Array.isArray(x)?x[1]:x?.price);if(n&&Number.isFinite(p))extras[n]=p});return{name:raw.name||BASE[id]?.name||id,available:raw.available!==false,sizes:Object.keys(sizes).length?sizes:BASE[id]?.sizes||{},extras:Object.keys(extras).length?extras:BASE[id]?.extras||{}}}
function activePromo(promos,id){const d=new Date().toISOString().slice(0,10);return promos.find(p=>p.active!==false&&p.kind==='product'&&p.productId===id&&(!p.start||p.start<=d)&&(!p.end||p.end>=d))||null}
function unitPromo(base,p){if(!p)return base;if(p.type==='discount_percent')return Math.max(0,base*(1-Number(p.value||0)/100));if(p.type==='discount_fixed')return Math.max(0,base-Number(p.value||0));if(p.type==='set_price')return Math.max(0,Number(p.value||base));return base}
function priceCart(cart,products,promos){const out=[];let subtotal=0;for(const item of arr(cart)){const id=String(item.id||''),p=normaliseProduct(products[id],id);if(!p||p.available===false)throw Error(`${p?.name||id||'An item'} is currently unavailable.`);const sizeName=String(item.sizeName||String(item.detail||'').split(' · ')[0]||''),base=Number(p.sizes[sizeName]);if(!Number.isFinite(base))throw Error(`Choose a valid portion for ${p.name}.`);const extraNames=arr(item.extraNames),extras=extraNames.reduce((sum,n)=>{if(!(n in p.extras))throw Error(`An extra on ${p.name} is no longer available.`);return sum+Number(p.extras[n])},0),promo=activePromo(promos,id),unit=unitPromo(base,promo)+extras,q=Math.max(1,Math.min(50,Math.floor(Number(item.qty||1)))),freeUnits=promo?.type==='buy_x_get_y'?Math.floor(q/(Math.max(1,Number(promo.buyQty||2))+Math.max(1,Number(promo.freeQty||1))))*Math.max(1,Number(promo.freeQty||1)):0,line=unit*(q-freeUnits);subtotal+=line;out.push({...item,name:p.name,price:unit,qty:q,promoType:promo?.type||'',promoTitle:promo?.title||'',freebie:promo?.type==='free_item'?(promo.freeItem||'Free item'):'',lineTotal:line})}subtotal=Math.round(subtotal*100)/100;const processingFee=Math.round(subtotal*.0295*100)/100,total=Math.round((subtotal+processingFee)*100)/100;return{items:out,subtotal,processingFee,total}}
module.exports={BASE,priceCart};