const BASE={
'shawarma':{name:'Signature Shawarma',sizes:{'Lite':45,'Classic':55,'District Max':70},extras:{'Extra Chicken':8,'Extra Sausage':4,'Mixed Protein':12,'Extra Sauce':5,'Extra Cheese':10}},
'loaded-fries':{name:'Loaded Fries',sizes:{'Regular':70,'Medium':80,'Large':90},extras:{'Extra Chicken':15,'Extra Cheese':10,'Extra Sauce':10}},
'loaded-angwamo':{name:'Loaded Angwamo',sizes:{'Basic':60,'Classic':70,'Max · 5 Proteins':85},extras:{'Egg':6,'Sausage':8,'Chicken':15}},
'fried-rice':{name:'Fried Rice',sizes:{'Regular':65,'Classic':75,'District Max':85},extras:{'Extra Chicken':15,'Fried Egg':6,'Extra Sauce':5}},
'loaded-jollof':{name:'Loaded Jollof',sizes:{'Loaded Jollof':85},extras:{'Chicken':15,'Egg':6}},
'noodles':{name:'Noodles',sizes:{'Noodles':50},extras:{'Chicken':15,'Sausage':8,'Egg':6}},
'salad':{name:'District Salad',sizes:{'Regular':40,'Big Bowl':50,'District Bowl':55},extras:{}},
'burger':{name:'District Burger',sizes:{'Original':50,'Double District':60,'Big District':70},extras:{'Extra Patty':18,'Cheese':10,'Sausage':8,'Extra Sauce':5,'Fried Egg':6}},
'drink-coke':{name:'Coca Cola',sizes:{'Bottle':10},extras:{},isDrink:true,image:'images/coke.jpg'},
'drink-fanta':{name:'Fanta',sizes:{'Bottle':10},extras:{},isDrink:true,image:'images/fanta.jpg'},
'drink-sprite':{name:'Sprite',sizes:{'Bottle':10},extras:{},isDrink:true,image:'images/sprite.jpg'},
'drink-water':{name:'Water',sizes:{'Bottle':5},extras:{},isDrink:true,image:'images/water.jpg'}
};
const arr=v=>Array.isArray(v)?v:[];
function normaliseProduct(raw,id){if(!raw)return BASE[id];const sizes={};arr(raw.sizes).forEach(x=>{const n=Array.isArray(x)?x[0]:x?.name,p=Number(Array.isArray(x)?x[1]:x?.price);if(n&&Number.isFinite(p))sizes[n]=p});const extras={};arr(raw.extras).forEach(x=>{const n=Array.isArray(x)?x[0]:x?.name,p=Number(Array.isArray(x)?x[1]:x?.price);if(n&&Number.isFinite(p))extras[n]=p});return{id,name:raw.name||BASE[id]?.name||id,image:raw.image||BASE[id]?.image||'',isDrink:!!(raw.isDrink||BASE[id]?.isDrink),available:raw.available!==false,sizes:Object.keys(sizes).length?sizes:BASE[id]?.sizes||{},extras:Object.keys(extras).length?extras:BASE[id]?.extras||{}}}
function activePromo(promos,id){const d=new Date().toISOString().slice(0,10);return promos.find(p=>p.active!==false&&p.kind==='product'&&String(p.productId)===String(id)&&(!p.start||p.start<=d)&&(!p.end||p.end>=d))||null}
function unitPromo(base,p){if(!p)return base;if(p.type==='discount_percent')return Math.max(0,base*(1-Number(p.value||0)/100));if(p.type==='discount_fixed')return Math.max(0,base-Number(p.value||0));if(p.type==='set_price')return Math.max(0,Number(p.value||base));return base}
function giftProduct(p,products){if(p?.freeItemId&&products[p.freeItemId])return {id:p.freeItemId,...products[p.freeItemId]};const wanted=String(p?.freeItem||'').toLowerCase();for(const [id,row] of Object.entries(products)){if(String(row?.name||'').toLowerCase()===wanted)return{id,...row}}return null}
function priceCart(cart,products,promos){const out=[],promoSummary=[];let subtotal=0,promoSavings=0;const baseCart=arr(cart).filter(x=>!x.promoGift);for(const item of baseCart){const id=String(item.id||''),p=normaliseProduct(products[id],id);if(!p||p.available===false)throw Error(`${p?.name||id||'An item'} is currently unavailable.`);const sizeName=String(item.sizeName||String(item.detail||'').split(' · ')[0]||''),base=Number(p.sizes[sizeName]);if(!Number.isFinite(base))throw Error(`Choose a valid portion for ${p.name}.`);const extraNames=arr(item.extraNames),extras=extraNames.reduce((sum,n)=>{if(!(n in p.extras))throw Error(`An extra on ${p.name} is no longer available.`);return sum+Number(p.extras[n])},0),promo=activePromo(promos,id),promoBase=unitPromo(base,promo),unit=promoBase+extras,q=Math.max(1,Math.min(50,Math.floor(Number(item.qty||1)))),buy=Math.max(1,Number(promo?.buyQty||2)),free=Math.max(1,Number(promo?.freeQty||1)),freeUnits=promo?.type==='buy_x_get_y'?Math.floor(q/(buy+free))*free:0,line=unit*(q-freeUnits),normal=(base+extras)*q,savings=Math.max(0,normal-line);subtotal+=line;promoSavings+=savings;const promoTitle=promo?.title||'',row={...item,id,name:p.name,price:unit,qty:q,promoId:promo?.id||'',promoType:promo?.type||'',promoTitle,promoMessage:promo?.message||promo?.subtitle||'',promoStart:promo?.start||'',promoEnd:promo?.end||'',promoFreeUnits:freeUnits,promoSavings:Math.round(savings*100)/100,lineTotal:Math.round(line*100)/100};out.push(row);if(promo&&promo.type==='free_item'){const qualify=Math.max(1,Number(promo.buyQty||1)),giftQty=Math.floor(q/qualify)*Math.max(1,Number(promo.freeQty||1)),rawGift=giftProduct(promo,products);if(giftQty>0&&rawGift){const gift=normaliseProduct(rawGift,rawGift.id),entries=Object.entries(gift.sizes||{}),first=entries[0];if(!gift||gift.available===false||!first)throw Error(`${rawGift.name||'The promotional gift'} is currently unavailable.`);const giftValue=Number(first[1]||0)*giftQty;promoSavings+=giftValue;out.push({id:rawGift.id,name:gift.name,price:0,basePrice:Number(first[1]||0),qty:giftQty,detail:`Promo gift · ${first[0]}`,sizeName:first[0],extraNames:[],itemNote:'',image:rawGift.image||'',isDrink:!!rawGift.isDrink,promoGift:true,promoId:promo.id||'',promoType:'free_item',promoTitle:promoTitle||`Free ${gift.name}`,promoMessage:promo.message||promo.subtitle||'',promoStart:promo.start||'',promoEnd:promo.end||'',promoSavings:Math.round(giftValue*100)/100,lineTotal:0,sourceProductId:id})}}
if(promo){const summary=promoTitle||promo.badge||`${promo.type} promotion`;if(summary&&!promoSummary.includes(summary))promoSummary.push(summary)}}subtotal=Math.round(subtotal*100)/100;promoSavings=Math.round(promoSavings*100)/100;const processingFee=Math.round(subtotal*.0295*100)/100,total=Math.round((subtotal+processingFee)*100)/100;return{items:out,subtotal,processingFee,total,promoSavings,promoSummary}}
module.exports={BASE,priceCart};