(() => {
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const store=window.WD_DB?.cache || {get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
  const money=n=>`GHS ${Number(n||0).toFixed(2).replace('.00','')}`;
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));

  function defaultTeam(){return window.WD_DEFAULT_TEAM||[]}
  function initDefaults(){
    const defaults={wdReviews:WD_DEFAULT_REVIEWS||[],wdPromos:WD_DEFAULT_PROMOS||[],wdSlides:WD_DEFAULT_SLIDES||[],wdProducts:WD_PRODUCTS||[],wdTeam:defaultTeam(),wdGallery:WD_IMAGE_LIST||[],wdOrders:[],wdDonations:[],wdContacts:[],wdSubscribers:[]};
    Object.entries(defaults).forEach(([k,v])=>{if(localStorage.getItem(k)===null)store.set(k,v)});
  }
  async function syncPublicData(){
    if(!window.WD_DB)return;
    const sets=[['menuItems','wdProducts',WD_PRODUCTS],['promotions','wdPromos',WD_DEFAULT_PROMOS],['heroSlides','wdSlides',WD_DEFAULT_SLIDES],['reviews','wdReviews',WD_DEFAULT_REVIEWS],['feedGallery','wdGallery',WD_IMAGE_LIST],['teamMembers','wdTeam',defaultTeam()]];
    await Promise.all(sets.map(async ([c,k,d])=>{let values=await WD_DB.list(c,k,d);if(k==='wdProducts'){const by=new Map(values.map(x=>[String(x.id),x]));WD_PRODUCTS.forEach(x=>{if(!by.has(String(x.id)))values.push(x)})}store.set(k,values)}));
    const settings=await WD_DB.getSettings(); if(settings&&Object.keys(settings).length)store.set('wdSettings',settings);
    document.dispatchEvent(new CustomEvent('wd:data-ready'));
  }

  function brand(){return `<span class="brand-wrap"><span>W</span><span class="rhat">R</span><span>AP</span></span><span class="brand-district">DISTRICT</span>`}
  function header(){
    const host=$('[data-site-header]');if(!host)return;const page=document.body.dataset.page||'';
    const nav=[['index.html','Home','home'],['menu.html','Menu','menu'],['deals.html','Promo','promo'],['about.html','District','about'],['feed-the-street.html','Feed the Street','feed'],['team.html','Team','team'],['contact.html','Contact','contact']];
    host.innerHTML=`<header class="site-header"><div class="nav-inner"><button class="menu-button" aria-label="Open menu"><span></span><span></span></button><a class="brand" href="index.html">${brand()}</a><nav class="desktop-nav">${nav.map(n=>`<a class="${page===n[2]?'active':''}" href="${n[0]}">${n[1]}</a>`).join('')}</nav><div class="nav-tools"><a class="btn btn-gold order-food" href="menu.html">Order food</a><button class="icon-button" data-open-cart aria-label="Open cart"><i class="fa-solid fa-bag-shopping"></i><span class="cart-count">0</span></button></div></div></header><nav class="mobile-nav">${nav.map(n=>`<a href="${n[0]}">${n[1]}</a>`).join('')}</nav>`;
    window.addEventListener('scroll',()=>$('.site-header')?.classList.toggle('scrolled',scrollY>20));
    $('.menu-button')?.addEventListener('click',()=>{$('.mobile-nav').classList.toggle('open');document.body.classList.toggle('no-scroll')});
  }
  function footer(){
    const host=$('[data-site-footer]');if(!host)return; const cfg={...WD_CONFIG.social,...store.get('wdSettings',{}).social};
    const social=(icon,url,label)=>url&&url!=='#'?`<a href="${url}" target="_blank" rel="noopener" aria-label="${label}"><i class="fa-brands fa-${icon}"></i></a>`:'';
    host.innerHTML=`<footer class="footer"><div class="wrap"><div class="footer-top"><div><span class="eyebrow">Come hungry</span><h2>See you in<br>the District.</h2></div><div><h3>Stay close to the kitchen.</h3><p class="lede">Promos, new menu moves and Feed the Street updates in your inbox.</p><form class="newsletter-form" data-newsletter><input required type="email" placeholder="Email address"><button aria-label="Subscribe"><i class="fa-solid fa-arrow-right"></i></button></form></div></div><div class="footer-grid"><div><a class="brand" href="index.html">${brand()}</a><p>Bold wraps, loaded boxes and proper comfort food made for serious cravings.</p><div class="socials">${social('snapchat',cfg.snapchat,'Snapchat')}${social('instagram',cfg.instagram,'Instagram')}${social('tiktok',cfg.tiktok,'TikTok')}${social('x-twitter',cfg.x,'X')}${social('facebook-f',cfg.facebook,'Facebook')}<a href="https://wa.me/${WD_CONFIG.whatsapp}" aria-label="WhatsApp"><i class="fa-brands fa-whatsapp"></i></a></div></div><div><h4>Explore</h4><p><a href="menu.html">Menu</a></p><p><a href="deals.html">Promo</a></p><p><a href="feed-the-street.html">Feed the Street</a></p></div><div><h4>Need help?</h4><p><a href="contact.html">Contact</a></p><p><a href="team.html">Team</a></p><p><a href="about.html">Our story</a></p><p><a href="contact.html#faqs">FAQs</a></p></div><div><h4>Order</h4><p>Pickup or delivery.</p><p>Delivery fees and timing are confirmed with your order.</p></div></div><div class="legal"><span>© 2026 Wrap District.</span><span>Site by <a class="powered-link" href="https://jvojames.netlify.app" target="_blank" rel="noopener">JVO_JAMES</a> · <a class="admin-link" href="admin.html">District Control</a></span></div></div></footer>`
  }
  function toast(msg){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2800)}
  function cart(){return store.get('wdCart',[])} function saveCart(c){store.set('wdCart',c);updateCartCount();renderCart()} function updateCartCount(){const n=cart().reduce((s,x)=>s+x.qty,0);$$('.cart-count').forEach(x=>x.textContent=n)}

  function drawerShells(){if(!$('#cartDrawer'))document.body.insertAdjacentHTML('beforeend',`<div class="drawer-backdrop"></div><aside class="drawer" id="cartDrawer"><div class="drawer-head"><h2>Your cart</h2><button class="drawer-close" data-close-drawer><i class="fa-solid fa-xmark"></i></button></div><div class="drawer-body" id="cartDrawerBody"></div><div class="drawer-foot"><div class="drawer-total"><span>Subtotal</span><span id="cartDrawerTotal">GHS 0</span></div><a class="btn btn-gold" style="width:100%" href="checkout.html">Checkout <i class="fa-solid fa-arrow-right"></i></a></div></aside><aside class="drawer" id="reviewDrawer"><div class="drawer-head"><h2>Add a review</h2><button class="drawer-close" data-close-drawer><i class="fa-solid fa-xmark"></i></button></div><div class="drawer-body"><p class="lede" style="font-size:15px">Tell us how it went. Your email stays private and is only used to confirm we received your review.</p><div class="review-success" id="reviewSuccess">Review received. Thank you.</div><form class="form-stack" id="reviewForm"><div class="field"><label>Name</label><input required name="name" placeholder="Your name"></div><div class="field"><label>Location</label><input required name="location" placeholder="Your area or town"></div><div class="field"><label>Email</label><input required type="email" name="email" placeholder="you@example.com"></div><div class="field"><label>Rating</label><div class="rating-picker" data-rating>${[1,2,3,4,5].map(i=>`<button type="button" data-star="${i}">★</button>`).join('')}</div></div><div class="field"><label>Review</label><textarea required minlength="10" name="text" placeholder="What did you order and how did it go?"></textarea></div><label class="check-row"><input required type="checkbox" name="purchased"><span>I confirm that I purchased a product from Wrap District.</span></label><button class="btn btn-gold" type="submit">Submit review</button></form></div></aside><div class="modal" id="reviewModal"><div class="modal-card"><button class="modal-close" data-close-modal><i class="fa-solid fa-xmark"></i></button><div id="reviewModalContent"></div></div></div>`)}
  function openDrawer(id){$('.drawer-backdrop').classList.add('open');$(id).classList.add('open');document.body.classList.add('no-scroll')} function closeDrawers(){$$('.drawer,.drawer-backdrop').forEach(x=>x.classList.remove('open'));document.body.classList.remove('no-scroll')}
  function renderCart(){const b=$('#cartDrawerBody'),t=$('#cartDrawerTotal');if(!b)return;const c=cart();if(!c.length){b.innerHTML='<div class="empty-state"><i class="fa-solid fa-bag-shopping fa-2x"></i><h3>Your cart is hungry.</h3><p>Pick something good and come back.</p><a class="btn btn-gold" href="menu.html">Open the menu</a></div>';t.textContent=money(0);return}b.innerHTML=c.map((x,i)=>`<div class="cart-item"><div class="cart-thumb"><img src="${x.image}" alt=""><button class="remove-item" data-remove="${i}">Remove</button></div><div><h4>${x.name}</h4><small>${x.detail||''}</small><div class="qty"><button data-q="-1" data-i="${i}">−</button><b>${x.qty}</b><button data-q="1" data-i="${i}">+</button></div></div><b>${money(x.price*x.qty)}</b></div>`).join('');t.textContent=money(c.reduce((s,x)=>s+x.price*x.qty,0));$$('[data-q]',b).forEach(btn=>btn.onclick=()=>{const a=cart(),i=+btn.dataset.i;a[i].qty+=+btn.dataset.q;if(a[i].qty<1)a.splice(i,1);saveCart(a)});$$('[data-remove]',b).forEach(btn=>btn.onclick=()=>{const a=cart();a.splice(+btn.dataset.remove,1);saveCart(a);toast('Removed from cart')})}
  function reviews(){const rail=$('[data-reviews]');if(!rail)return;const rs=store.get('wdReviews',[]).filter(r=>r.approved);rail.innerHTML=rs.map((r,i)=>`<article class="review-card"><div class="stars">${'★'.repeat(r.stars)}</div><h3>${r.name}</h3><small>${r.location||'Ghana'}</small><p class="review-text">${r.text}</p>${r.text.length>120?`<button data-review-more="${i}">Read more</button>`:''}</article>`).join('');$$('[data-review-more]',rail).forEach(btn=>btn.onclick=()=>{const r=rs[+btn.dataset.reviewMore];$('#reviewModalContent').innerHTML=`<div class="stars" style="color:var(--gold)">${'★'.repeat(r.stars)}</div><h2 style="font:400 42px Anton;text-transform:uppercase">${r.name}</h2><p style="color:#aaa">${r.location||''}</p><p style="line-height:1.7">${r.text}</p>`;$('#reviewModal').classList.add('open')})}

  async function sendEmail(type,params={}){
    try{
      const c=WD_CONFIG?.emailjs;if(!window.emailjs||!c||String(c.publicKey).startsWith('YOUR_'))return false;
      emailjs.init({publicKey:c.publicKey});
      const base={...params,event_type:type,business_email:WD_CONFIG.businessEmail,site_name:'Wrap District'};
      await emailjs.send(c.serviceId,c.templates.customer,base);
      if(['purchase','donation','contact'].includes(type)){
        await sleep(1100); // EmailJS browser SDK rate limit: one request per second.
        await emailjs.send(c.serviceId,c.templates.admin,{...base,recipient_type:'admin'});
      }
      return true;
    }catch(e){console.warn('Email notification failed',e);return false}
  }
  function reviewForm(){let stars=5;$$('[data-star]').forEach(b=>b.onclick=()=>{stars=+b.dataset.star;$$('[data-star]').forEach(x=>x.style.opacity=(+x.dataset.star<=stars?'1':'.25'))});$('#reviewForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),row={id:'r'+Date.now(),name:f.get('name'),location:f.get('location'),email:f.get('email'),stars,text:f.get('text'),purchased:true,approved:false,date:new Date().toISOString()};await WD_DB?.save('reviews',row.id,row,'wdReviews');await sendEmail('feedback',{customer_name:row.name,customer_email:row.email,customer_location:row.location,review_text:row.text,rating:stars});e.target.reset();stars=5;$('#reviewSuccess').style.display='block';toast('Review submitted successfully')})}
  function newsletter(){$('[data-newsletter]')?.addEventListener('submit',async e=>{e.preventDefault();const email=e.target.querySelector('input[type=email]').value,id=btoa(email.toLowerCase()).replace(/[^a-z0-9]/gi,'').slice(0,28)||String(Date.now());await WD_DB?.save('subscribers',id,{email,date:new Date().toISOString()},'wdSubscribers');await sendEmail('subscription',{customer_email:email,subscriber_email:email});toast('You’re on the list.');e.target.reset()})}

  initDefaults();header();footer();drawerShells();updateCartCount();renderCart();reviews();reviewForm();newsletter();
  document.addEventListener('wd:data-ready',()=>{reviews();footer()});
  document.addEventListener('click',e=>{if(e.target.closest('[data-open-cart]'))openDrawer('#cartDrawer');if(e.target.closest('[data-open-review]')){$('#reviewSuccess').style.display='none';openDrawer('#reviewDrawer')}if(e.target.closest('[data-close-drawer]')||e.target.classList.contains('drawer-backdrop'))closeDrawers();if(e.target.closest('[data-close-modal]')||e.target.id==='reviewModal')$('#reviewModal')?.classList.remove('open')});
  syncPublicData();

  window.WD={store,money,toast,cart,saveCart,openDrawer,sendEmail,db:WD_DB,addCart(item){const c=cart(),key=`${item.id}|${item.detail||''}`,found=c.find(x=>x.key===key);found?found.qty++:c.push({...item,key,qty:1});saveCart(c);toast(`${item.name} added to cart`)},products(){return store.get('wdProducts',WD_PRODUCTS||[])},slides(){return store.get('wdSlides',WD_DEFAULT_SLIDES||[])},promos(){const today=new Date().toISOString().slice(0,10);return store.get('wdPromos',WD_DEFAULT_PROMOS||[]).map(p=>({...p,active:p.active!==false&&(!p.start||p.start<=today)&&(!p.end||p.end>=today)}))},team(){return store.get('wdTeam',defaultTeam())},gallery(){return [...store.get('wdGallery',WD_IMAGE_LIST||[])].sort((a,b)=>Number((typeof a==='string'?9999:a.position)??9999)-Number((typeof b==='string'?9999:b.position)??9999))}};
})();
