(() => {
  const c=WD.cart(),subtotal=c.reduce((s,x)=>s+x.price*x.qty,0),fee=Math.round(subtotal*.0295*100)/100,total=subtotal+fee,$=s=>document.querySelector(s);
  $('#checkoutItems').innerHTML=c.length?c.map(x=>`<div class="checkout-item"><img src="${x.image}" alt=""><div><b>${x.name}</b><br><small>${x.detail||''}</small></div><b>${WD.money(x.price*x.qty)}</b></div>`).join(''):'<p>Your cart is empty. <a href="menu.html">Choose something first.</a></p>';
  $('#subtotal').textContent=WD.money(subtotal);$('#fee').textContent=WD.money(fee);$('#total').textContent=WD.money(total);
  let mode='delivery';document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;$('#addressField').classList.toggle('hidden',mode==='pickup');refresh()});
  const form=$('#checkoutForm'),button=$('#payButton');
  function refresh(){const valid=form.checkValidity()&&(mode==='pickup'||form.address.value.trim());button.classList.toggle('ready',!!valid);button.querySelector('span:last-child').textContent=valid?'Pay securely with Paystack':'Complete your details to pay'}form.addEventListener('input',refresh);refresh();
  form.onsubmit=e=>{e.preventDefault();if(!c.length)return WD.toast('Your cart is empty.');if(WD.store.get('wdOpen',true)===false)return WD.toast('Orders are temporarily paused.');if(mode==='delivery'&&!form.address.value.trim())return WD.toast('Add your delivery address.');const key=WD_CONFIG.paystackPublicKey;if(!window.PaystackPop||String(key).startsWith('YOUR_'))return WD.toast('Paystack is not configured yet. Add your public key in config.js.');
    const fd=new FormData(form),orderId='WD-'+Date.now().toString().slice(-8),record={id:orderId,customer:fd.get('name'),phone:fd.get('phone'),email:fd.get('email'),address:fd.get('address')||'',note:fd.get('note')||'',type:mode,subtotal,processingFee:fee,total,status:'New',date:new Date().toISOString(),items:c};
    button.disabled=true;button.querySelector('span:last-child').textContent='Opening secure payment…';
    const pop=new PaystackPop();pop.newTransaction({key,email:record.email,amount:Math.round(total*100),currency:'GHS',channels:['card','mobile_money'],metadata:{custom_fields:[{display_name:'Order',variable_name:'order_id',value:orderId},{display_name:'Fulfilment',variable_name:'fulfilment',value:mode}]},onSuccess:async t=>{try{record.reference=t.reference;record.paymentStatus='Paid';await WD_DB.save('orders',orderId,record,'wdOrders');await WD.sendEmail('purchase',{order_id:orderId,customer_name:record.customer,customer_phone:record.phone,customer_email:record.email,fulfilment:mode,delivery_address:record.address,order_items:c.map(x=>`${x.qty}x ${x.name} - ${x.detail||''}`).join('\n'),order_subtotal:WD.money(subtotal),processing_fee:WD.money(fee),order_total:WD.money(total),payment_reference:t.reference});WD.saveCart([]);location.href=`index.html?order=${encodeURIComponent(orderId)}`}catch(err){button.disabled=false;refresh();WD.toast('Payment succeeded, but saving the order failed. Keep your Paystack reference: '+t.reference)}},onCancel:()=>{button.disabled=false;refresh();WD.toast('Payment was not completed.')},onError:err=>{button.disabled=false;refresh();WD.toast(err?.message||'Payment could not start.')}})
  };
})();
