window.WD_PRODUCTS = [
{id:'shawarma',name:'Signature Shawarma',category:'Shawarma',from:45,tagline:'Rolled hot, packed proper.',description:'Warm flatbread, seasoned chicken, crisp vegetables and our creamy house sauces, rolled fresh when you order.',image:WD_IMAGES.productShawarma,sizeImages:[WD_IMAGES.productShawarma,WD_IMAGES.productShawarma,WD_IMAGES.productShawarma],sizes:[['Lite',45],['Classic',55],['District Max',70]],extras:[['Extra Chicken',8,WD_IMAGES.extraChicken2],['Extra Sausage',4,WD_IMAGES.extraSausage],['Mixed Protein',12,WD_IMAGES.extraMixed],['Extra Sauce',5,WD_IMAGES.extraSauce],['Extra Cheese',10,WD_IMAGES.extraCheese]],available:true},
{id:'loaded-fries',name:'Loaded Fries',category:'Loaded Fries',from:70,tagline:'Crispy underneath. Serious on top.',description:'Golden fries with chicken, cheese, onions, herbs and sauce. Big flavour from the first fork to the last.',image:WD_IMAGES.productLoadedFries,sizeImages:[WD_IMAGES.productLoadedFries,WD_IMAGES.productLoadedFries,WD_IMAGES.productLoadedFries],sizes:[['Regular',70],['Medium',80],['Large',90]],extras:[['Extra Chicken',15,WD_IMAGES.extraChicken2],['Extra Cheese',10,WD_IMAGES.extraCheese],['Extra Sauce',10,WD_IMAGES.extraSauce]],available:true},
{id:'loaded-angwamo',name:'Loaded Angwamo',category:'Ghanaian',from:60,tagline:'The comfort food that came dressed up.',description:'Smoky angwamo layered with protein, egg and extras for a familiar plate with a louder finish.',image:WD_IMAGES.productLoadedAngwamo,sizeImages:[WD_IMAGES.productLoadedAngwamo,WD_IMAGES.productLoadedAngwamo,WD_IMAGES.productLoadedAngwamo],sizes:[['Basic',60],['Classic',70],['Max · 5 Proteins',85]],extras:[['Egg',6,WD_IMAGES.extraEgg],['Sausage',8,WD_IMAGES.extraSausage],['Chicken',15,WD_IMAGES.extraChicken]],available:true},
{id:'fried-rice',name:'Fried Rice',category:'Rice',from:65,tagline:'Hot wok, full plate, clean finish.',description:'Fragrant fried rice tossed hot with vegetables and served in portions made for real appetites.',image:WD_IMAGES.productFriedRice,sizeImages:[WD_IMAGES.productFriedRice,WD_IMAGES.productFriedRice,WD_IMAGES.productFriedRice],sizes:[['Regular',65],['Classic',75],['District Max',85]],extras:[['Extra Chicken',15,WD_IMAGES.extraChicken],['Fried Egg',6,WD_IMAGES.extraFriedEgg],['Extra Sauce',5,WD_IMAGES.extraSauce]],available:true},
{id:'loaded-jollof',name:'Loaded Jollof',category:'Jollof',from:85,tagline:'Red, rich and ready for business.',description:'A generous serving of jollof with protein and the extras that turn a good plate into a proper one.',image:WD_IMAGES.productLoadedJollof,sizeImages:[WD_IMAGES.productLoadedJollof],sizes:[['Loaded Jollof',85]],extras:[['Chicken',15,WD_IMAGES.extraChicken],['Egg',6,WD_IMAGES.extraEgg]],available:true},
{id:'noodles',name:'Noodles',category:'Noodles',from:50,tagline:'Saucy, quick and hard to share.',description:'Stir-fried noodles, vegetables and bold seasoning for the kind of craving that needs an answer now.',image:WD_IMAGES.productNoodles,sizeImages:[WD_IMAGES.productNoodles],sizes:[['Noodles',50]],extras:[['Chicken',15,WD_IMAGES.extraChicken],['Sausage',8,WD_IMAGES.extraSausage],['Egg',6,WD_IMAGES.extraEgg]],available:true},
{id:'salad',name:'District Salad',category:'Salad',from:40,tagline:'Fresh, full and definitely not a side.',description:'A proper salad loaded with chicken, sausages, tuna flakes, baked beans and extra sauces. Pick the portion that matches your appetite.',image:WD_IMAGES.productSalad,sizeImages:[WD_IMAGES.productSalad,'images/salad2.jpg','images/salad3.jpg'],sizes:[['Regular',40],['Big Bowl',50],['District Bowl',55]],extras:[],available:true,newProduct:true},
{id:'burger',name:'District Burger',category:'Burger',from:50,tagline:'New to the District. Built to make noise.',description:'A big, juicy burger with layers that actually show up. Choose your size, stack on the extras and make it yours.',image:WD_IMAGES.productBurger,sizeImages:[WD_IMAGES.productBurger,WD_IMAGES.productBurger,WD_IMAGES.productBurger],sizes:[['Original',50],['Double District',60],['Big District',70]],extras:[['Extra Patty',18,'images/placeholder-food.svg'],['Cheese',10,WD_IMAGES.extraCheese],['Sausage',8,WD_IMAGES.extraSausage],['Extra Sauce',5,WD_IMAGES.extraSauce],['Fried Egg',6,WD_IMAGES.extraFriedEgg]],available:true,newProduct:true,featured:true}
];
window.WD_MENU_ORDER=['shawarma','loaded-fries','loaded-angwamo','fried-rice','loaded-jollof','noodles','salad','burger'];
window.WD_DEFAULT_TEAM=[
{id:'t1',name:'Kenneth Kankam',role:'Founder',image:WD_IMAGES.teamFounder,bio:'Kenneth founded Wrap District and leads the food from idea to final plate. He develops the menu, protects the standard and keeps the District moving with purpose.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t6',name:'Cynara',role:'Team',image:WD_IMAGES.teamCynara,bio:'Cynara brings a thoughtful eye, fresh ideas and calm energy to the people behind the District.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t4',name:'James',role:'Web Developer',image:WD_IMAGES.teamJames,bio:'James built and develops the Wrap District website, shaping the digital experience customers use to discover the menu, order, pay and stay connected to the brand.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t2',name:'Sheila',role:'Team',image:WD_IMAGES.teamSheila,bio:'Sheila brings energy, ideas and a steady presence to the team as the District keeps growing.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t3',name:'Nafred',role:'Team',image:WD_IMAGES.teamNafred,bio:'Nafred helps shape the spirit of Wrap District with perspective, support and good energy.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t5',name:'Etornam',role:'Team',image:WD_IMAGES.teamEtornam,bio:'Etornam brings ideas, personality and a thoughtful point of view to the team.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t7',name:'Elizabeth',role:'Team',image:WD_IMAGES.teamElizabeth,bio:'Elizabeth brings care, support and consistency to the work that keeps the District moving.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t8',name:'Rigobert',role:'Team',image:WD_IMAGES.teamRigobert,bio:'Rigobert brings creativity, presence and a strong sense of how the District should be seen and remembered.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''}
];
window.WD_DEFAULT_REVIEWS=[];
window.WD_DEFAULT_PROMOS=[];
window.WD_DEFAULT_SLIDES=[
{id:'s1',kicker:'Craving handled',title:'WRAPPED. LOADED. READY.',copy:'Big shawarma, hot fries and the kind of sauces that make silence happen at the first bite.',image:WD_IMAGES.homeHeroShawarma,cta:'Order shawarma',href:'order.html?product=shawarma'},
{id:'s2',kicker:'Fork first',title:'FRIES WITH MAIN CHARACTER ENERGY.',copy:'Crispy fries loaded with chicken, cheese and sauce. No sad corners in the box.',image:WD_IMAGES.homeHeroFries,cta:'Load a box',href:'order.html?product=loaded-fries'},
{id:'s3',kicker:'Proper plate',title:'RICE THAT CAME TO WORK.',copy:'Fried rice, jollof and angwamo built for lunch, late nights and everything in between.',image:WD_IMAGES.homeHeroRice,cta:'See the menu',href:'menu.html'},
{id:'s4',kicker:'Quick fix',title:'NOODLES. SAUCE. PEACE.',copy:'Fast, savoury and very easy to finish before you realise you were meant to share.',image:WD_IMAGES.homeHeroNoodles,cta:'Build your bowl',href:'order.html?product=noodles'},
{id:'s5',kicker:'Beyond the kitchen',title:'A GOOD MEAL CAN TRAVEL FURTHER.',copy:'Feed the Street turns support into plates, people and moments that matter.',image:WD_IMAGES.homeHeroCommunity,cta:'See the journey',href:'feed-the-street.html'}];
window.WD_DEFAULT_INVENTORY=[];
