window.WD_PRODUCTS = [
{id:'shawarma',name:'Signature Shawarma',category:'Shawarma',from:45,tagline:'Rolled hot, packed proper.',description:'Warm flatbread, seasoned chicken, crisp vegetables and our creamy house sauces, rolled fresh when you order.',image:WD_IMAGES.productShawarma,sizeImages:[WD_IMAGES.sizeLite,WD_IMAGES.sizeClassic,WD_IMAGES.sizeMax],sizes:[['Lite',45],['Classic',55],['District Max',70]],extras:[['Extra Chicken',8,WD_IMAGES.extraChicken2],['Extra Sausage',4,WD_IMAGES.extraSausage],['Mixed',12,WD_IMAGES.extraMixed],['Extra Sauce',5,WD_IMAGES.extraSauce],['Extra Cheese',10,WD_IMAGES.extraCheese]],customizable:true,available:true},
{id:'loaded-fries',name:'Loaded Fries',category:'Loaded Fries',from:70,tagline:'Crispy underneath. Serious on top.',description:'Golden fries with chicken, cheese, onions, herbs and sauce. Big flavour from the first fork to the last.',image:WD_IMAGES.productLoadedFries,sizeImages:[WD_IMAGES.sizeLite,WD_IMAGES.sizeClassic,WD_IMAGES.sizeMax],sizes:[['Regular',70],['Medium',80],['Large',90]],extras:[['Extra Chicken',15,WD_IMAGES.extraChicken2],['Extra Cheese',10,WD_IMAGES.extraCheese],['Extra Sauce',10,WD_IMAGES.extraSauce]],customizable:true,available:true},
{id:'fried-rice',name:'Fried Rice',category:'Rice',from:65,tagline:'Hot wok, full plate, clean finish.',description:'Fragrant fried rice tossed hot with vegetables and served in portions made for real appetites.',image:WD_IMAGES.productFriedRice,sizeImages:[WD_IMAGES.sizeLite,WD_IMAGES.sizeClassic,WD_IMAGES.sizeMax],sizes:[['Regular',65],['Classic',75],['District Max',85]],extras:[['Extra Chicken',15,WD_IMAGES.extraChicken],['Fried Egg',6,WD_IMAGES.extraFriedEgg],['Extra Sauce',5,WD_IMAGES.extraSauce]],available:true},
{id:'loaded-angwamo',name:'Loaded Angwamo',category:'Ghanaian',from:60,tagline:'The comfort food that came dressed up.',description:'Smoky angwamo layered with protein, egg and extras for a familiar plate with a louder finish.',image:WD_IMAGES.productLoadedAngwamo,sizeImages:[WD_IMAGES.sizeLite,WD_IMAGES.sizeClassic,WD_IMAGES.sizeMax],sizes:[['Basic',60],['Classic',70],['Max · 5 Proteins',85]],extras:[['Egg',6,WD_IMAGES.extraEgg],['Sausage',8,WD_IMAGES.extraSausage],['Chicken',15,WD_IMAGES.extraChicken]],available:true},
{id:'loaded-jollof',name:'Loaded Jollof',category:'Jollof',from:85,tagline:'Red, rich and ready for business.',description:'A generous serving of jollof with protein and the extras that turn a good plate into a proper one.',image:WD_IMAGES.productLoadedJollof,sizeImages:[WD_IMAGES.productLoadedJollof],sizes:[['Loaded Jollof',85]],extras:[['Chicken',15,WD_IMAGES.extraChicken],['Egg',6,WD_IMAGES.extraEgg]],available:true},
{id:'noodles',name:'Noodles',category:'Noodles',from:50,tagline:'Saucy, quick and hard to share.',description:'Stir-fried noodles, vegetables and bold seasoning for the kind of craving that needs an answer now.',image:WD_IMAGES.productNoodles,sizeImages:[WD_IMAGES.productNoodles],sizes:[['Noodles',50]],extras:[['Chicken',15,WD_IMAGES.extraChicken],['Sausage',8,WD_IMAGES.extraSausage],['Egg',6,WD_IMAGES.extraEgg]],available:true},
{id:'salad',name:'District Salad',category:'Salad',from:40,tagline:'Fresh, full and definitely not a side.',description:'A proper salad loaded with chicken, sausages, tuna flakes, baked beans and extra sauces. Pick the portion that matches your appetite. Everything good is already inside.',image:WD_IMAGES.productSalad,sizeImages:[WD_IMAGES.sizeLite,WD_IMAGES.sizeClassic,WD_IMAGES.sizeMax],sizes:[['Regular',40],['Big Bowl',50],['District Bowl',55]],extras:[],available:true,newProduct:true},
{id:'burger',name:'District Burger',category:'Burger',from:50,tagline:'New to the District. Built to make noise.',description:'A big, juicy burger with layers that actually show up. Choose your size, stack on the extras and make the first Wrap District burger your own.',image:WD_IMAGES.productBurger,sizeImages:[WD_IMAGES.sizeLite,WD_IMAGES.sizeClassic,WD_IMAGES.sizeMax],sizes:[['Original',50],['Double District',60],['Big District',70]],extras:[['Extra Patty',18,WD_IMAGES.extraChicken2],['Cheese',10,WD_IMAGES.extraCheese],['Sausage',8,WD_IMAGES.extraSausage],['Extra Sauce',5,WD_IMAGES.extraSauce],['Fried Egg',6,WD_IMAGES.extraFriedEgg]],available:true,newProduct:true,featured:true}
];

window.WD_DEFAULT_TEAM=[
{id:'t1',name:'Kenneth Kankam',role:'Founder',image:WD_IMAGES.teamFounder,bio:'Kenneth founded Wrap District and leads the food side of the brand from idea to final plate. He cooks, develops the menu and keeps the standard clear as the District grows.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t2',name:'Sheila',role:'Team',image:WD_IMAGES.teamSheila,bio:'Sheila helps keep Wrap District present, consistent and connected with the people who follow the brand.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t3',name:'Nafred',role:'Team',image:WD_IMAGES.teamNafred,bio:'Nafred brings energy, ideas and support to the team as Wrap District grows its food and community work.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t4',name:'James',role:'Web Developer',image:WD_IMAGES.teamJames,bio:'James designed and developed the Wrap District website, shaping the digital experience from browsing the menu to ordering and managing the site.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t5',name:'Etornam',role:'Team',image:WD_IMAGES.teamEtornam,bio:'Etornam supports the team with ideas and helps the brand stay active and connected across its public channels.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t6',name:'Cynara',role:'Team',image:WD_IMAGES.teamCynara,bio:'Cynara adds a thoughtful eye to how Wrap District shows up and helps keep the brand connected with its audience.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t7',name:'Elizabeth',role:'Assistant Cook',image:WD_IMAGES.teamElizabeth,bio:'Elizabeth works closely with Kenneth in the kitchen, helping with preparation and keeping service moving when orders come in.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''},
{id:'t8',name:'Rigobert',role:'Team',image:WD_IMAGES.teamRigobert,bio:'Rigobert helps document and share the moments that matter around Wrap District, especially the people and community around the brand.',instagram:'#',tiktok:'#',snapchat:'',x:'',facebook:''}
];
window.WD_DEFAULT_REVIEWS=[
{id:'r1',name:'Nana A.',location:'Tema',email:'',stars:5,text:'The shawarma was packed properly and the sauce was perfect. I ordered Classic and immediately understood the hype.',approved:true,purchased:true,date:'2026-07-17'},
{id:'r2',name:'Esi K.',location:'Prampram',email:'',stars:5,text:'Loaded fries arrived hot, generous and very filling. Definitely ordering the large next time.',approved:true,purchased:true,date:'2026-07-28'},
{id:'r3',name:'Kojo M.',location:'Community 25',email:'',stars:5,text:'The angwamo is serious food. Proper portion and the flavours actually come through. It felt familiar but still had its own personality.',approved:true,purchased:true,date:'2026-08-03'},
{id:'r4',name:'Ama S.',location:'Tema',email:'',stars:4,text:'Smooth ordering, quick communication and the fried rice was really good. Extra sauce sealed it for me.',approved:true,purchased:true,date:'2026-08-09'},
{id:'r5',name:'Jay O.',location:'Dawhenya',email:'',stars:5,text:'Jollof portion is not playing at all. Rich, filling and worth it.',approved:true,purchased:true,date:'2026-08-14'}];
window.WD_DEFAULT_PROMOS=[{id:'p1',title:'Friday Wrap Run',subtitle:'Grab two Classic Shawarmas and get a sauce upgrade on us.',active:true,start:'',end:'',image:WD_IMAGES.promoFridayWrap,cta:'Order the promo'}];
window.WD_DEFAULT_SLIDES=[
{id:'s1',kicker:'Craving handled',title:'WRAPPED. LOADED. READY.',copy:'Big shawarma, hot fries and the kind of sauces that make silence happen at the first bite.',image:WD_IMAGES.homeHeroShawarma,cta:'Order shawarma',href:'order.html?product=shawarma'},
{id:'s2',kicker:'Fork first',title:'FRIES WITH MAIN CHARACTER ENERGY.',copy:'Crispy fries loaded with chicken, cheese and sauce. No sad corners in the box.',image:WD_IMAGES.homeHeroFries,cta:'Load a box',href:'order.html?product=loaded-fries'},
{id:'s3',kicker:'Proper plate',title:'RICE THAT CAME TO WORK.',copy:'Fried rice, jollof and angwamo built for lunch, late nights and everything in between.',image:WD_IMAGES.homeHeroRice,cta:'See the menu',href:'menu.html'},
{id:'s4',kicker:'Quick fix',title:'NOODLES. SAUCE. PEACE.',copy:'Fast, savoury and very easy to finish before you realise you were meant to share.',image:WD_IMAGES.homeHeroNoodles,cta:'Build your bowl',href:'order.html?product=noodles'},
{id:'s5',kicker:'Beyond the kitchen',title:'A GOOD MEAL CAN TRAVEL FURTHER.',copy:'Feed the Street turns support into plates, people and moments that matter.',image:WD_IMAGES.homeHeroCommunity,cta:'See the journey',href:'feed-the-street.html'}];

window.WD_DEFAULT_INVENTORY=[
{id:'inv-chicken',name:'Chicken',unit:'portions',quantity:40,lowAt:12},
{id:'inv-sausage',name:'Sausages',unit:'pieces',quantity:55,lowAt:15},
{id:'inv-cheese',name:'Cheese',unit:'slices',quantity:45,lowAt:12},
{id:'inv-sauce',name:'House sauce',unit:'servings',quantity:60,lowAt:18},
{id:'inv-wraps',name:'Wrap bread',unit:'pieces',quantity:35,lowAt:10},
{id:'inv-burger-buns',name:'Burger buns',unit:'pieces',quantity:28,lowAt:10}
];
