(() => {
  const $=s=>document.querySelector(s);
  $('#feedHero').style.backgroundImage=`url("${WD_IMAGES.feedHero}")`;
  $('#feedStoryImage').src=WD_IMAGES.feedStory; $('#feedBandImage').src=WD_IMAGES.feedVisualBand;
  let imgs=[];
  function renderGallery(){imgs=WD.gallery().map(x=>typeof x==='string'?x:x.url).filter(Boolean);const g=$('#feedGallery');const preview=[...imgs,...imgs];g.innerHTML=preview.map((x,i)=>`<button data-photo="${i%imgs.length}"><img src="${x}" alt="Feed the Street moment ${(i%imgs.length)+1}" loading="lazy"></button>`).join('');g.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>openPhoto(+b.dataset.photo))}
  const box=$('#lightbox'),main=$('#lightboxImage'),thumbs=$('#lightboxThumbs');
  function openPhoto(i){main.src=imgs[i];thumbs.innerHTML=imgs.map((x,n)=>`<button class="${n===i?'active':''}" data-thumb="${n}"><img src="${x}" alt=""></button>`).join('');box.classList.add('open');document.body.classList.add('no-scroll');thumbs.querySelectorAll('[data-thumb]').forEach(b=>b.onclick=()=>openPhoto(+b.dataset.thumb))}
  $('#lightboxClose').onclick=closeLightbox;box.onclick=e=>{if(e.target===box)closeLightbox()};function closeLightbox(){box.classList.remove('open');document.body.classList.remove('no-scroll')}
  renderGallery();document.addEventListener('wd:data-ready',renderGallery);

  const form=$('#donationForm'),success=$('#donationSuccess');let lastDonation=null;
  const showSuccess=d=>{lastDonation=d;$('#donationSuccessText').innerHTML=`Thank you, <strong>${d.name}</strong>. Your <strong>${WD.money(d.amount)}</strong> contribution is now part of the next Feed the Street outreach.`;$('#donationReference').textContent=`Payment reference: ${d.reference}`;success.classList.add('open');document.body.classList.add('no-scroll')};
  document.querySelectorAll('[data-donation-close]').forEach(b=>b.onclick=()=>{success.classList.remove('open');document.body.classList.remove('no-scroll')});
  form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),amount=Number(fd.get('amount')),email=String(fd.get('email')).trim(),name=String(fd.get('name')||'Friend of the District').trim(),key=WD_CONFIG.paystackPublicKey,id='FTS-'+Date.now().toString().slice(-8);if(!amount||amount<1)return WD.toast('Enter a valid donation amount.');if(!window.PaystackPop||String(key).startsWith('YOUR_'))return WD.toast('Add your Paystack public key in config.js before accepting donations.');const popup=new PaystackPop();popup.newTransaction({key,email,amount:Math.round(amount*100),currency:'GHS',channels:['card','mobile_money'],metadata:{custom_fields:[{display_name:'Campaign',variable_name:'campaign',value:'Feed the Street'},{display_name:'Donation ID',variable_name:'donation_id',value:id},{display_name:'Donor name',variable_name:'donor_name',value:name},{display_name:'Donor email',variable_name:'donor_email',value:email}]},onSuccess:async t=>{const d={id,name,email,amount,reference:t.reference,date:new Date().toISOString(),status:'Paid'};try{await WD_DB.save('donations',id,d,'wdDonations')}catch(err){console.warn('Donation is verified by Paystack; webhook will sync it.',err)}await WD.sendEmail('donation',{donation_id:id,donor_name:name,customer_name:name,donor_email:email,customer_email:email,amount:WD.money(amount),payment_reference:t.reference});form.reset();showSuccess(d)},onCancel:()=>WD.toast('Donation payment was not completed.'),onError:err=>WD.toast(err?.message||'Payment could not start.')})});

  $('#downloadThankYou').onclick=()=>{if(!lastDonation)return;const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a5',orientation:'portrait'});const w=148,h=210;doc.setFillColor(18,15,13);doc.rect(0,0,w,h,'F');doc.setFillColor(248,200,78);doc.circle(124,22,28,'F');doc.setFillColor(217,54,43);doc.circle(16,190,36,'F');doc.setDrawColor(255,255,255);doc.setLineWidth(.5);doc.roundedRect(10,10,w-20,h-20,6,6,'S');doc.setTextColor(248,200,78);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('WRAP DISTRICT · FEED THE STREET',16,26);doc.setTextColor(255,255,255);doc.setFontSize(28);doc.text('THANK',16,55);doc.text('YOU.',16,67);doc.setFont('helvetica','normal');doc.setFontSize(11);const line=`${lastDonation.name}, your ${WD.money(lastDonation.amount)} contribution helps us prepare and share more thoughtful meals with children in our community.`;doc.text(doc.splitTextToSize(line,110),16,88);doc.setFillColor(255,243,223);doc.roundedRect(16,118,116,40,4,4,'F');doc.setTextColor(17,15,13);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('YOUR SUPPORT',23,130);doc.setFontSize(20);doc.text(WD.money(lastDonation.amount),23,143);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(`Reference: ${lastDonation.reference}`,23,151);doc.setTextColor(255,255,255);doc.setFontSize(9);doc.text('A good meal can travel further.',16,178);doc.setFontSize(7);doc.text(`Generated ${new Date().toLocaleDateString()} · wrapdistrict-gh`,16,184);doc.save(`Wrap-District-Thank-You-${lastDonation.id}.pdf`)};
})();
