(() => {
 const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function ordered(){const by=new Map(WD.products().map(p=>[p.id,p]));return (window.WD_MENU_ORDER||[]).map(id=>by.get(id)).filter(Boolean)}
 function renderHero(){const hero=$('#heroSlides');if(!hero)return;const all=WD.slides().filter(x=>x.active!==false),admin=all.filter(x=>x.admin),base=all.filter(x=>!x.admin),normal=admin.length?[...admin,...base]:base,pp=WD.activePromos?.().find(x=>x.kind==='campaign')||WD.activePromos?.()[0],product=pp?.productId?WD.products().find(x=>x.id===pp.productId):null,promoSlide=pp?{promo:true,kicker:'LIVE PROMO · '+WD.promoDateLabel(pp),title:pp.title||WD.promoOfferLabel(pp),copy:pp.message||pp.subtitle||WD.promoOfferLabel(pp),image:pp.image||product?.image||WD_IMAGES.promoFallback,cta:'Claim the offer',href:WD.promoHref(pp),offer:WD.promoOfferLabel(pp)}:null,slides=promoSlide?[promoSlide,...normal]:normal;if(!slides.length)return;hero.innerHTML=slides.map((s,i)=>`<div class="hero-slide ${i?'':'active'} ${s.promo?'promo-hero-slide':''}"><img src="${esc(s.image)}" alt=""><div class="hero-copy">${s.promo?`<span class="hero-promo-chip"><i class="fa-solid fa-bolt"></i> ${esc(s.offer)}</span>`:''}<span class="eyebrow">${esc(s.kicker||'Wrap District')}</span><h1 class="display">${s.promo?esc(s.title):String(s.title).replace(/([.!?]) /g,'$1<br>').replace('WRAPPED. LOADED. READY.','WRAPPED.<br><span>LOADED.</span><br>READY.')}</h1><p>${esc(s.copy||'')}</p><div class="hero-actions"><a class="btn btn-gold" href="${esc(s.href||'menu.html')}">${esc(s.cta||'Order now')} <i class="fa-solid fa-arrow-right"></i></a>${s.promo?'<a class="btn btn-ghost" href="deals.html">Promo details</a>':'<a class="btn btn-ghost" href="menu.html">See full menu</a>'}</div></div></div>`).join('')+`<div class="hero-dots">${slides.map((_,i)=>`<button class="${i?'':'active'}" data-slide="${i}" aria-label="Show slide ${i+1}"></button>`).join('')}</div>`;let cur=0,t;const show=i=>{cur=(i+slides.length)%slides.length;$$('.hero-slide',hero).forEach((x,n)=>x.classList.toggle('active',n===cur));$$('[data-slide]',hero).forEach((x,n)=>x.classList.toggle('active',n===cur));clearInterval(t);t=setInterval(()=>show(cur+1),6500)};$$('[data-slide]',hero).forEach(b=>b.onclick=()=>show(+b.dataset.slide));show(0)}
 function promoBadge(p){const promo=WD.activeProductPromo?.(p.id);return promo?`<span class="promo-burst"><small>LIVE PROMO</small>${esc(promo.badge||WD.promoOfferLabel(promo)||'PROMO')}</span>`:''}
 function renderMenu(){const menu=$('#homeMenu');if(!menu)return;const ps=ordered().filter(p=>p.available!==false);menu.innerHTML=ps.map(p=>{const promo=WD.activeProductPromo?.(p.id);return `<a class="food-tile menu-mosaic-card ${promo?'has-live-promo':''}" href="order.html?product=${encodeURIComponent(p.id)}&from=menu"><img src="${esc(p.image)}" alt="${esc(p.name)}">${promoBadge(p)}<div class="food-info mosaic-copy"><div><h3>${esc(p.name)}</h3><span class="mosaic-price">${WD.productPriceLabel?.(p)||`From ${WD.money(p.from)}`}</span>${promo?`<span class="card-promo-copy">${esc(WD.promoOfferLabel(promo))} · ${esc(WD.promoDateLabel(promo))}</span>`:''}</div><span class="mosaic-arrow"><i class="fa-solid fa-arrow-up-right-from-square"></i></span></div></a>`}).join('')}
 function renderPromo(){const promo=$('[data-home-promo]');if(!promo)return;const p=WD.activePromos?.()[0];promo.innerHTML=p?`<span class="eyebrow">LIVE PROMO · ${esc(WD.promoDateLabel(p))}</span><h2>${esc(p.title)}</h2><p>${esc(p.message||p.subtitle||WD.promoOfferLabel(p))}</p><a class="btn btn-gold" href="${WD.promoHref(p)}">Claim offer <i class="fa-solid fa-arrow-right"></i></a>`:'<span class="eyebrow">Promo</span><h2>Something good is cooking.</h2><p>When a District offer goes live, you will see it here.</p>'}
 function applyImages(){const d=$('.danger-image'),s=$('.street-photo');if(d)d.style.backgroundImage=`url("${WD_IMAGES.homeBuildSection}")`;if(s)s.style.backgroundImage=`url("${WD_IMAGES.homeFeedStreet}")`}
 function render(){renderHero();renderMenu();renderPromo();applyImages()}render();document.addEventListener('wd:data-ready',render);
})();